---
title: "Novel research that will disrupt the industry"
author: "Mr scientist"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  github_document:
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, warning = F, message = F, cache = T)
set.seed(1)
options(scipen = 999)

if (!require("pacman")) install.packages("pacman")

packages <- c(
  "tidyverse", # best thing that happend to me
  "dbplyr", # dplyr syntax for DB query
  "data.table", # only way to run grouped calculations on tons of groups
  "pander" # pretty table rendering
)

if (!require("pacman")) install.packages("pacman")
pacman::p_load(char = packages)
```

# Load data

```{r be sure to label chunks in an informative way}
source("../passwords.R") # never post your passwords to Github again!

```

# Don't be afraid to add headers along the report  
## They'll all show up in the table of contents!  

# There's also plots and tables all around

```{r show a plot}
plot(mtcars$mpg, mtcars$cyl)
```

```{r show a table}
pandoc.table(head(mtcars[, 1:4]))
```

